from pathlib import Path

path = Path(r"src/screens/PlannerScreen.tsx")
text = path.read_text()
old = "        <View style={styles.datesRow}>\n          <TouchableOpacity\n            style={styles.dateColumn}\n            onPress={() => setShowStartPicker(true)}\n          >\n            <TextInput\n              label=\"Arrive\"\n              value={formattedStart}\n              editable={false}\n              pointerEvents=\"none\"\n              mode=\"outlined\"\n              right={<TextInput.Icon icon=\"calendar\" />}\n            />\n          </TouchableOpacity>\n          <TouchableOpacity\n            style={styles.dateColumn}\n            onPress={() => setShowEndPicker(true)}\n          >\n            <TextInput\n              label=\"Depart\"\n              value={formattedEnd}\n              editable={false}\n              pointerEvents=\"none\"\n              mode=\"outlined\"\n              right={<TextInput.Icon icon=\"calendar\" />}\n            />\n          </TouchableOpacity>\n        </View>\n\n"
new = "        <View style={styles.dayPlanToggleRow}>\n          <Text variant=\"bodyMedium\" style={styles.dayPlanToggleLabel}>\n            Plan just one day?\n          </Text>\n          <Switch value={form.isDayPlan} onValueChange={handleToggleDayPlan} />\n        </View>\n\n        <View style={styles.datesRow}>\n          <TouchableOpacity\n            style={styles.dateColumn}\n            onPress={() => setShowStartPicker(true)}\n          >\n            <TextInput\n              label=\"Arrive\"\n              value={formattedStart}\n              editable={false}\n              pointerEvents=\"none\"\n              mode=\"outlined\"\n              right={<TextInput.Icon icon=\"calendar\" />}\n            />\n          </TouchableOpacity>\n          {!form.isDayPlan ? (\n            <TouchableOpacity\n              style={styles.dateColumn}\n              onPress={() => setShowEndPicker(true)}\n            >\n              <TextInput\n                label=\"Depart\"\n                value={formattedEnd}\n                editable={false}\n                pointerEvents=\"none\"\n                mode=\"outlined\"\n                right={<TextInput.Icon icon=\"calendar\" />}\n              />\n            </TouchableOpacity>\n          ) : null}\n        </View>\n\n"
if old not in text:
    raise SystemExit('old block not found for replacement')
text = text.replace(old, new)
path.write_text(text)
